# Message d'exemple
# Contient le numero de la chanson a jouer
# Notre variable entiere pourra prendre plusieurs valeurs 
#    0 : Chanson numero 0
#    1 : Chanson numero 1
#    2 : Chanson numero 2 
#    3 : Bruit desagreable

uint8 TITRE0                 = 0
uint8 TITRE1                = 1
uint8 TITRE2                = 2
uint8 BRUIT_DESAGREABLE     = 3

# Declaration de la variable
uint8 value

