# Message d’exemple
# Contient le numéro de la chanson à jouer
# Notre variable entière pourra prendre plusieurs valeurs 
#    0 : Chanson numéro 0
#    1 : Chanson numéro 1
#    2 : Chanson numéro 2 
#    3 : Bruit désagréable

uint8 TITRE0                 = 0
uint8 TITRE1                = 1
uint8 TITRE2                = 2
uint8 BRUIT_DESAGREABLE     = 3

# Déclaration de la variable
uint8 value

